server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: user

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.sansam.user.**

cloud:
  aws:
    s3:
      bucket: sansamforce
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

# log
logging:
  file:
    path: C:/logs/team-msa/user

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka