spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: jdbc:log4jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    root: info
    org.springframework.web: info
    com.zaxxer.hikari: info
    log4jdbc.log4j2: error
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    jdbc.connection: info

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion : none