services:
  mysql:
    image: mysql:latest
    container_name: mysqldb_sansam
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_sansam
    restart: always
    environment:
      PMA_HOST: mysqldb_sansam
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8090:80"
    networks:
      - springboot-network

  mongo:
    image: mongo
    container_name: mongo_sansam
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - springboot-network

#  server:
#    container_name: server_sansam
#    build: ./server
#    hostname: server_sansam
#    ports:
#      - "8761:8761"
#    networks:
#      - cloud-network

#  config-server:
#    container_name: config_sansam
#    build: ./config-server
#    ports:
#      - "8888:8888"
#    networks:
#      - cloud-network

#  gateway:
#    container_name: gateway_sansam
#    build: ./gateway
#    ports:
#      - "8000:8000"
#    networks:
#      - cloud-network

#  user:
#    container_name: user_sansam
#    build: ./user
#    ports:
#      - "0:8000"
#    networks:
#      - cloud-network
#    depends_on:
#      - config-server
#
#  team:
#    container_name: team_sansam
#    build: ./team
#    ports:
#      - "0:8000"
#    networks:
#      - cloud-network
#  order:
#    build: ./order
#    ports:
#      - "0:8000"
#    networks:
#      - cloud-network
#    depends_on:
#      - config-server

#  spring:
#    build:
#      context: ./toyProject
#      dockerfile: DockerFile
#    depends_on:
#      - mysql
#    ports:
#      - "8084:8084"

volumes:
  db_data:
  mongodb-data:

networks:
  springboot-network:
    driver: bridge
  cloud-network:
    driver: bridge