services:
  mysql:
    image: mysql:latest
    container_name: mysqldb_sansam
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cloud-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_sansam
    restart: always
    environment:
      PMA_HOST: mysqldb_sansam
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8090:80"
    networks:
      - cloud-network

  mongo:
    image: mongo
    container_name: mongo_sansam
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - cloud-network

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - cloud-network

  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - cloud-network

#  config-server:
#    container_name: config_sansam
#    build: ./config-server
#    ports:
#      - "8888:8888"
#    networks:
#      - cloud-network

  user-service:
    container_name: user_service
    hostname: user-service
    build: ./user-service
    ports:
      - "0:8000"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    env_file:
      - .env
    networks:
      - cloud-network

#
#  team:
#    container_name: team_sansam
#    build: ./team
#    ports:
#      - "0:8000"
#    networks:
#      - cloud-network


volumes:
  db_data:
  mongodb-data:

networks:
  springboot-network:
    driver: bridge
  cloud-network:
    driver: bridge