server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
#            - RewritePath=/api/v1/user/(?<segment>.*), /user/$\{segment}
        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/v1/team/**
          filters:
            - AuthorizationHeaderFilter
#            - RewritePath=/api/v1/team/(?<segment>.*), /$\{segment}
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/project/**
          filters:
            - AuthorizationHeaderFilter
#            - RewritePath=/api/v1/project/(?<segment>.*), /$\{segment}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka