server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/api/v1/user/(?<segment>.*), /$\{segment}
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/v1/team/**
          filters:
            - RewritePath=/api/v1/team/(?<segment>.*), /$\{segment}
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/v1/project/**
          filters:
            - RewritePath=/api/v1/project/(?<segment>.*), /$\{segment}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka