server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
#          uri: file:///C:\config
          uri: https://github.com/SansamForce/team-building.git